services:
  web:
    image: debian:13
    container_name: kompi
    hostname: kompi
    network_mode: "host"
    volumes:
      - ./scripts:/scripts
      - ./www:/www
    command: ["/bin/bash", "/scripts/main.sh"]
    restart: unless-stopped
