services:
  web:
    image: debian:13
    container_name: kompi
    hostname: kompi
    ports:
      - "8080:8080"
    volumes:
      - ./scripts:/scripts
      - ./www:/www
    command: ["/bin/bash", "/scripts/main.sh"]
    restart: unless-stopped
